<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <title>La Plume Digitale</title>
  <!-- CSS global -->
  <link rel="stylesheet" href="css/style.css" />
</head>
<body>
  <header>
    <h1>La Plume Digitale</h1>
    <div class="navigation">
      <nav class="bouton-navigation">
        <a href="index.php?action=accueil">Accueil</a>
        <a href="index.php?action=livres">Livres</a>
        <a href="index.php?action=contact">Contact</a>
      </nav>
      <div class="search-bar">
        <input type="text" placeholder="Appuyez pour chercher">
      </div>
    </div>
  </header>

  <nav> 
    <p>Ceci sera le menu !!!!</p>
    <a href="index.php?action=accueil">Accueil</a>
    <a href="index.php?action=chercher">Chercher</a>
    <a href="index.php?action=contact">Contact</a>
  </nav>
