<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title> A la bonne page </title>
    <link rel="stylesheet" href=" ../css/style.css" />
    <link rel="icon" type="image/png" href="../img/logo.png">
  </head>
  <body>
   <header>
        <h1>La Plume Digitale</h1>
        <div class="navigation">
            <nav class="bouton-navigation">
              <a href="./index.php?action=accueil">Accueil</a>
              <a href="./index.php?action=chercher">chercher</a>
              <a href="./index.php?action=contact">contact</a>
              <a href="./index.php?action=connect">connect</a>
            </nav>
            <div class="search-bar">
                <input type="text" placeholder="Appuyez pour chercher">
            </div>
        </div>
    </header>
