<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title> xxx </title>
    <link rel="stylesheet" href=" xxx  " />
  </head>
  <body>
   <header>
        <h1>La Plume Digitale</h1>
        <div class="navigation">
            <nav class="bouton-navigation">
                <a href="/index.html">Accueil</a>
                <a href="/html/all-books.html">Livre</a>
                <a href="/html/contact.html">Contacter</a>
            </nav>
            <div class="search-bar">
                <input type="text" placeholder="Appuyez pour chercher">
            </div>
        </div>
    </header>
