<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title> Accueil </title>
    <link rel="stylesheet" type="text/css" href="../css/style.css"/>
  </head>
  <body>
   <header>
        <h1> A la bonne page</h1>
        <img src="../img/logo.png" alt="Logo" class="logo" style="width: 300px; height: auto;">
        <div class="navigation">
            <nav class="bouton-navigation">
                <a href="/index.html">Accueil</a>
                <a href="/html/all-books.html">Chercher</a>
                <a href="/html/contact.html">Contact</a>
            </nav>
            <div class="search-bar">
                <input type="text" placeholder="Appuyez pour chercher">
            </div>
        </div>
    </header>
     <nav> 
       <p>Ceci sera le menu !!!!</p>
      </nav>